version: "3.8"

services:
  tensorflow:
    image: tensorflow/tensorflow:latest-gpu
    command: /bin/bash
    stdin_open: true
    tty: true
    build: .
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]